/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFileChooser;
import Controlador.ControladorGuiPrincipal;
import Negocio.AdministradorAutomatas;
import Negocio.AutomataDigito;
import Negocio.AutomataIdentificador;
import Negocio.AutomataLetra;
import Negocio.AutomatadeSimbolo;
import javax.swing.JOptionPane;
/**
 *
 * @author felipe
 */
public class GuiPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form GuiPrincipal
     */
    private JFileChooser fileCho;
    private ControladorGuiPrincipal guiCon;
    
    
    
    public GuiPrincipal() {
        initComponents();
        fileCho=new JFileChooser();
        guiCon=new ControladorGuiPrincipal(new AdministradorAutomatas(new AutomataLetra(new int[1]),new AutomataDigito(new int[1]), new AutomataIdentificador(new int[1]),new AutomatadeSimbolo(new int[1])));
        guiCon.createTabIni();
        guiCon.loadTable();
        jtSimbol.setModel(guiCon.getTab());
        btnSearchTab.setEnabled(false);
        btnAnalizarSInta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscaArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSimbol = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txSourceCod = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txObje = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAnalizaArchivo = new javax.swing.JButton();
        lbSintac = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAnalizarSInta = new javax.swing.JButton();
        btnSearchTab = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSintOutput = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscaArchivo.setText("Cargar Archivo");
        btnBuscaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaArchivoActionPerformed(evt);
            }
        });

        jtSimbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSimbol);

        txSourceCod.setColumns(20);
        txSourceCod.setRows(5);
        jScrollPane2.setViewportView(txSourceCod);

        txObje.setColumns(20);
        txObje.setRows(5);
        jScrollPane3.setViewportView(txObje);

        jLabel1.setText("Archivo Objeto");

        jLabel2.setText("Tabla de Simbolos");

        jLabel3.setText("Archivo Fuente");

        btnAnalizaArchivo.setText("Analizar Archivo");
        btnAnalizaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizaArchivoActionPerformed(evt);
            }
        });

        lbSintac.setText("Analizador Sintactico");

        jPanel2.setBackground(new java.awt.Color(140, 120, 99));

        btnAnalizarSInta.setText("Analizar Archivo SINT");
        btnAnalizarSInta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarSIntaActionPerformed(evt);
            }
        });

        btnSearchTab.setText("BuscaTabla");
        btnSearchTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTabActionPerformed(evt);
            }
        });

        tbSintOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbSintOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAnalizarSInta)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchTab))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizarSInta)
                    .addComponent(btnSearchTab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(lbSintac))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscaArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalizaArchivo)
                        .addGap(416, 416, 416))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(lbSintac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(168, 168, 168)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnalizaArchivo)
                    .addComponent(btnBuscaArchivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaArchivoActionPerformed
        // TODO add your handling code here:
        txSourceCod.setText("");
        fileCho.showOpenDialog(this);
        if(fileCho.getSelectedFile()!=null){
        guiCon.loadFile(fileCho.getSelectedFile());
        txSourceCod.append(guiCon.getTextSourceFile());
        }
    }//GEN-LAST:event_btnBuscaArchivoActionPerformed

    private void btnAnalizaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizaArchivoActionPerformed
        // TODO add your handling code here:
        if(fileCho.getSelectedFile()!=null){
            guiCon.StarALEX();
            txObje.append(guiCon.getTextObjFil());
            jtSimbol.removeAll();
            guiCon.loadTable();
            jtSimbol.setModel(guiCon.getTab());
            JOptionPane.showMessageDialog(this,"archivo de salida en la siguiente direccion:"+guiCon.getPatchObjetFile());
            btnSearchTab.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnalizaArchivoActionPerformed

    private void btnAnalizarSIntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarSIntaActionPerformed
        guiCon.startASINT();
        guiCon.loadSinTab(guiCon.getEstados());
        tbSintOutput.setModel(guiCon.getTableASINT());
    }//GEN-LAST:event_btnAnalizarSIntaActionPerformed

    private void btnSearchTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTabActionPerformed
        fileCho.showOpenDialog(this);
        if(fileCho.getSelectedFile() != null){
            guiCon.loadFile(fileCho.getSelectedFile());
            btnAnalizarSInta.setEnabled(true);
        } 
    }//GEN-LAST:event_btnSearchTabActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizaArchivo;
    private javax.swing.JButton btnAnalizarSInta;
    private javax.swing.JButton btnBuscaArchivo;
    private javax.swing.JButton btnSearchTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtSimbol;
    private javax.swing.JLabel lbSintac;
    private javax.swing.JTable tbSintOutput;
    private javax.swing.JTextArea txObje;
    private javax.swing.JTextArea txSourceCod;
    // End of variables declaration//GEN-END:variables

    
}
